apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required "Must provide a storage class name." .Values.storageClass.name}}-xfs
  annotations:
    "helm.sh/resource-policy": keep
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: {{ required "Must provide a storage class reclaim policy." .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  storagepool: {{ required "Must provide a VxFlex OS storage pool name." .Values.storagePool }}
  FsType: xfs
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: csi-vxflexos.dellemc.com/{{ required "Must provide the VxFlex OS system Name." .Values.systemName }}
    values:
    - csi-vxflexos.dellemc.com

    
