apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vxflexos-xfs
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  storagepool: <STORAGE_POOL>   #Insert Storage pool.
  FsType: xfs
  systemID: <SYSTEM_ID>   #Insert System ID
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: csi-vxflexos.dellemc.com/<SYSTEM_ID>  #Insert System ID.
    values:
    - csi-vxflexos.dellemc.com

    
