apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vxflexos-xfs
provisioner: csi-vxflexos.dellemc.com
# reclaimPolicy: PVs that are dynamically created by a StorageClass will have the reclaim policy specified here
# Allowed values:
#   Reclaim: retain the PV after PVC deletion
#   Delete: delete the PV after PVC deletion
# Optional: true
# Default value: Delete
reclaimPolicy: Delete
# allowVolumeExpansion: allows the users to resize the volume by editing the corresponding PVC object
# Allowed values:
#   true: allow users to resize the PVC
#   false: does not allow users to resize the PVC
# Optional: true
# Default value: false
allowVolumeExpansion: true
parameters:
  # Storage pool to use on system
  # Optional: false
  storagepool: <STORAGE_POOL> # Insert Storage pool
  # Protection domain that storage pool above belongs to
  # Needed if array has two storagepools that share the same name, but belong to different protection domains
  # Optional: true
  # Uncomment the line below if you want to use protectiondomain
  # protectiondomain: # Insert Protection domain name
  # System you would like this storage class to use
  # Allowed values: one string for system ID
  # Optional: false
  systemID: <SYSTEM_ID> # Insert System ID
  # format options to pass to mkfs
  # Allowed values: A string dictating the fs options you want passed
  # Optional: true
  # Uncomment the line below if you want to use mkfsFormatOption
  # mkfsFormatOption: "<mkfs_format_option>" # Insert file system format option
  # Filesytem type for volumes created by storageclass
  # Default value: None if defaultFsType is not mentioned in values.yaml
  # Else defaultFsType value mentioned in values.yaml
  # will be used as default value
  csi.storage.k8s.io/fstype: xfs
# volumeBindingMode determines how volume binding and dynamic provisioning should occur
# Allowed values:
#  Immediate: volume binding and dynamic provisioning occurs once PVC is created
#  WaitForFirstConsumer: delay the binding and provisioning of PV until a pod using the PVC is created.
# Optional: false
# Default value: WaitForFirstConsumer (required for topology section below)
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies helps scheduling pods on worker nodes which match all of below expressions.
allowedTopologies:
- matchLabelExpressions:
  - key: csi-vxflexos.dellemc.com/<SYSTEM_ID> # Insert System ID
    values:
    - csi-vxflexos.dellemc.com    
