apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerflex-pvc-with-vac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: vxflexos
  volumeAttributesClassName: powerflex-qos
