name: Weekly License Header Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:
jobs:
  license-check:
    name: Run License Header Checker
    uses: harishp8889/test-common-github-actions/.github/workflows/license-checker.yaml@main
    secrets: inherit
